"""
environment.py
──────────────
Thermal model for the server room.

Physics modelled (simplified Newton's law of cooling + server heat load):

  dT/dt = (1/C) * [ Q_servers(traffic) - Q_cooling(ac, fan) - Q_leak(T_in, T_out) ]

Where:
  C             = thermal capacitance of the room (°C / W·s)
  Q_servers     = heat generated by servers (W), scales with traffic load
  Q_cooling     = heat removed by AC + fans (W)
  Q_leak        = passive heat exchange with outdoor via walls (W)

State:
  indoor_temp   – current rack temperature (°C)
  traffic_load  – 0.0 – 1.0, simulates server CPU utilization pattern
"""

import math
import random
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

# ── Room constants ────────────────────────────────────────────────────────────
ROOM_THERMAL_CAPACITANCE = 180.0   # seconds to heat/cool 1°C per watt
MAX_SERVER_HEAT_W        = 4500.0  # max heat output at full traffic
WALL_CONDUCTANCE         = 0.8     # W/°C — how fast outdoor temp leaks in

# ── Cooling power per action ──────────────────────────────────────────────────
COOLING_MAP = {
    "ac_high":   3800.0,   # W of cooling
    "ac_medium": 2200.0,
    "ac_low":    1000.0,
    "fan_only":   300.0,
    "off":          0.0,
}

# ── Traffic schedule: hour → base load (0.0–1.0) ─────────────────────────────
# Hyderabad IST office hours + night batch jobs
TRAFFIC_SCHEDULE = {
    0: 0.20, 1: 0.15, 2: 0.15, 3: 0.18, 4: 0.20,
    5: 0.25, 6: 0.30, 7: 0.45, 8: 0.65,
    9: 0.82, 10: 0.88, 11: 0.90, 12: 0.85,
    13: 0.75, 14: 0.88, 15: 0.92, 16: 0.90,
    17: 0.78, 18: 0.60, 19: 0.50, 20: 0.45,
    21: 0.40, 22: 0.32, 23: 0.25,
}


class Environment:
    def __init__(self, initial_temp: float = 26.0):
        self.indoor_temp   = initial_temp
        self.traffic_load  = 0.4
        self._tick         = 0          # number of 5-second ticks elapsed

    # ── Public API ────────────────────────────────────────────────────────────

    def step(self, action: str, outdoor_temp: float, dt: float = 5.0) -> dict:
        """
        Advance the thermal model by `dt` seconds.

        Args:
            action:       one of COOLING_MAP keys
            outdoor_temp: current outdoor temperature (°C)
            dt:           seconds since last call (default 5)

        Returns:
            dict with indoor_temp, traffic_load, server_heat_w, cooling_w
        """
        self._tick += 1
        self._update_traffic()

        server_heat  = self._server_heat()
        cooling      = COOLING_MAP.get(action, COOLING_MAP["fan_only"])
        leak         = WALL_CONDUCTANCE * (outdoor_temp - self.indoor_temp)

        net_heat     = server_heat - cooling + leak             # W
        delta_temp   = (net_heat / ROOM_THERMAL_CAPACITANCE) * dt
        self.indoor_temp = round(self.indoor_temp + delta_temp + random.gauss(0, 0.05), 2)
        self.indoor_temp = max(15.0, min(50.0, self.indoor_temp))   # physical clamp

        logger.debug(
            f"tick={self._tick} action={action} "
            f"T_in={self.indoor_temp:.2f} traffic={self.traffic_load:.2f} "
            f"server_heat={server_heat:.0f}W cooling={cooling:.0f}W leak={leak:.1f}W"
        )

        return {
            "indoor_temp":    self.indoor_temp,
            "traffic_load":   round(self.traffic_load, 3),
            "server_heat_w":  round(server_heat, 1),
            "cooling_w":      float(cooling),
        }

    def get_temp(self) -> float:
        return self.indoor_temp

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _update_traffic(self):
        """
        Traffic follows an hourly schedule + random spikes + slow drift.
        """
        hour = datetime.now().hour
        base = TRAFFIC_SCHEDULE.get(hour, 0.5)

        # Random spikes (5 % chance each tick)
        spike = random.uniform(0.10, 0.25) if random.random() < 0.05 else 0.0

        # Smooth drift toward base
        self.traffic_load += 0.05 * (base - self.traffic_load) + random.gauss(0, 0.01) + spike
        self.traffic_load  = max(0.05, min(1.0, self.traffic_load))

    def _server_heat(self) -> float:
        """Heat (W) generated by servers at current traffic load."""
        return MAX_SERVER_HEAT_W * self.traffic_load


if __name__ == "__main__":
    import json
    logging.basicConfig(level=logging.DEBUG)
    env = Environment(initial_temp=28.0)
    for i in range(10):
        state = env.step("ac_medium", outdoor_temp=32.5)
        print(json.dumps(state))
